Se agrego el tipo de dato 'cadena' al lenguaje
ericknavarro/InterpreteSencillo pull request #11
Opened 2020-01-26 17:41 UTC by 201503440

Se agrego el tipo de dato 'cadena' al lenguaje y ahora se pueden declarar variables de dicho tipo.

Ejemplo:

cadena cad1;
cad1 = "probando cadena ..................";
imprimir(cad1);

Salida:

probando cadena ..................

2020-02-02 05:11 UTC, rjanixz commented
@201503440 una consulta, en la clase operación se hacen algunas comparaciones relacionales, por ejemplo: x > y.

En la implementación estos valores son convertidos a número, con la agregación de este nuevo tipo de dato, consideraste estas operaciones?

2020-02-06 03:44 UTC, 201503440 commented
@rjanixz la verdad no considere ese tipo de operaciones al agregar este tipo de dato.

 Ademas creo que también debí considerar que en este nuevo tipo a la hora de asignar únicamente deberían poder asignar cadenas y no números también.

2020-02-25 14:56 UTC, rjanixz requested changes
@201503440 Es necesario la implementación de esas validaciones, de lo contrario el proyecto quedará inestable.

2020-02-25 17:36 UTC, rjanixz requested changes
Realizar validaciones de tipos, en asiganciones, comparaciones, etc.

2020-02-25 17:37 UTC, rjanixz requested changes
Realizar validaciones de tipos, en asiganciones, comparaciones, etc.

2020-03-18 21:40 UTC, rjanixz commented
Se cierra pr por falta de respuesta en solicitud de cambios

2020-03-18 21:40 UTC, closed without merging