Validación al agregar objeto a la tabla de símbolos
ericknavarro/InterpreteSencillo pull request #13
Opened 2020-01-31 01:06 UTC by vkslax

Propuesta para la validación de la existencia de variable en la tabla de símbolos comentada en el issue 5

2020-02-02 05:06 UTC, rjanixz requested changes
@vkslax muchas gracias por tu propuesta, te puse unos comentarios por favor revisarlos. Saludos.

2020-02-02 05:06 UTC, rjanixz commented on src/arbol/TablaDeSimbolos.java
> +        if (returnValue == "Desconocido") System.out.println("La variable "+id+" no existe en este ámbito.");
cómo buena práctica de programación, usar una sola instrucción por línea y utilizar los corchetes para los bloques aunque este contenga solo una instrucción.

2020-02-02 05:06 UTC, rjanixz commented on src/arbol/TablaDeSimbolos.java
> +    private Object getValue(String id)
Esta función getValue puede mejorarse. Algunas observaciones:

La implementación es una copia de la versión original en la función `obtenerValor` en el cual tiene sentido devolver "Desconocido" sino se encuentra el valor ya que la intención de esa función es retornar un valor. Pero el propósito de esta nueva función es verificar si la variable (símbolo) ya ha sido definida o no; por lo cuál devolver el valor para hacer esta verificación no es una buena implementación.

Lo ideal sería hacer una función que devuelva true o false; ya que esta implementación fallará con la implementación del tipo de dato String (PR https://github.com/ericknavarro/InterpreteSencillo/pull/11)

Por ejemplo al definir `String cadena = "Desconocido"`

Recomiendo para la implementación de esta funcionalidad hacer override de la función [contains](https://docs.oracle.com/javase/8/docs/api/java/util/LinkedList.html#contains-java.lang.Object-) de esta manera puede ser utilizada para todos los tipos de datos futuros y en cualquier parte del proyecto.

Cualquier duda, a las ordenes

2020-02-06 22:13 UTC, vkslax commented
@rjanixz Se han realizado los cambios solicitados, con excepción del override de contains, el método en su lugar  fue sobrecargado para tener la validación por medio del id string requerido y mantener la funcionalidad original.

2020-02-25 18:16 UTC, rjanixz approved these changes

2020-02-25 18:16 UTC, merged